name = "Laconic"
uuid = "08136afe-955a-11e9-1da2-859b40bd8df4"
authors = ["David Eklund <deklund@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
